# Generated by Django 5.1.5 on 2025-02-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productreview_rating_alter_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
